services:
  app:
    build:
      context: .
    depends_on:
      - database
      - redis
    restart: always
    networks:
      mynet:
        ipv4_address: 10.5.0.3
    volumes:
     - "./images:/images"

  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
    networks:
      mynet:
        ipv4_address: 10.5.0.4
    ports:
      - 5432:5432
    volumes:
      - "./database/:/var/lib/postgresql/data"

  redis:
    image: redis:latest
    restart: always
    command: redis-server --requirepass 123
    ports:
      - 6379:6379
    networks:
      mynet:
        ipv4_address: 10.5.0.5
    
networks:
  mynet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1